app = "chaamo-backend"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"
  PORT = "8080"
  ENV = "production"
  APP_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0
    method = "GET"
    path = "/health"

[deploy]
  strategy = "immediate"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048
